name: Copy repo

on:
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Install stgit as crate
        run: cargo install stgit

      - name: Get our repo
        uses: actions/checkout@v4
        with:
          path: ours
        
      - name: Get upstream repo
        uses: actions/checkout@v4
        with:
          path: them
          repository: ${{ vars.UPSTREAM_ORG_REPO }}

      - name: Convert new upstream commits to patches

      - name: Cache patches
 
      - name: Update HEAD pointer

      - name: Combine patches with features

      - name: Integrate stable features
